import React from 'react';
import {
  Box,
  Typography,
  IconButton,
  Paper,
  Stack,
} from '@mui/material';
import {
  PlayArrow as PlayIcon,
  Pause as PauseIcon,
  SkipNext as NextIcon,
  SkipPrevious as PreviousIcon,
} from '@mui/icons-material';
import { motion } from 'framer-motion';

const Lockscreen = () => {
  return (
    <Box
      sx={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: `url(${process.env.PUBLIC_URL}/cover.png) no-repeat center center fixed`,
        backgroundSize: 'cover',
        position: 'relative',
        p: 3,
        '&::before': {
          content: '""',
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'linear-gradient(to bottom, rgba(12, 26, 26, 0.8), rgba(12, 26, 26, 0.5), rgba(12, 26, 26, 0.8))',
          zIndex: 1,
        },
      }}
    >
      <Box sx={{ position: 'relative', zIndex: 2, textAlign: 'center', mt: 4 }}>
        <Typography variant="h6" color="text.secondary" sx={{ color: 'white' }}>
          12:34
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ color: 'rgba(255, 255, 255, 0.7)' }}>
          Monday, March 18
        </Typography>
      </Box>

      <Box sx={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', zIndex: 2 }}>
        <Paper
          elevation={3}
          sx={{
            p: 4,
            background: 'rgba(255, 255, 255, 0.05)',
            backdropFilter: 'blur(10px)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: '16px',
            width: '100%',
            maxWidth: 400,
          }}
        >
          <Box sx={{ textAlign: 'center', mb: 4 }}>
            <Typography variant="h5" sx={{ mb: 1, color: 'white', fontWeight: 600 }}>
              Cozy Rainy Afternoon
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ color: 'rgba(255, 255, 255, 0.7)' }}>
              Generated by Ambiance AI
            </Typography>
          </Box>

          <Stack
            direction="row"
            spacing={3}
            justifyContent="center"
            alignItems="center"
          >
            <IconButton size="large" sx={{ color: 'white', background: 'rgba(255, 255, 255, 0.05)', borderRadius: '50%', '&:hover': { background: 'rgba(255, 255, 255, 0.1)' } }}>
              <PreviousIcon sx={{ fontSize: 28 }} />
            </IconButton>
            <IconButton
              size="large"
              sx={{
                width: 72,
                height: 72,
                background: 'linear-gradient(135deg, #2d9c93 0%, #1a5f5a 100%)',
                borderRadius: '50%',
                boxShadow: '0 8px 24px rgba(45, 156, 147, 0.3)',
                '&:hover': {
                  background: 'linear-gradient(135deg, #1a5f5a 0%, #2d9c93 100%)',
                  boxShadow: '0 12px 32px rgba(45, 156, 147, 0.4)',
                },
                color: 'white',
              }}
            >
              <PlayIcon sx={{ fontSize: 48 }} />
            </IconButton>
            <IconButton size="large" sx={{ color: 'white', background: 'rgba(255, 255, 255, 0.05)', borderRadius: '50%', '&:hover': { background: 'rgba(255, 255, 255, 0.1)' } }}>
              <NextIcon sx={{ fontSize: 28 }} />
            </IconButton>
          </Stack>
        </Paper>
      </Box>

      <Box sx={{ position: 'relative', zIndex: 2, textAlign: 'center', mb: 4 }}>
        <Typography variant="body2" color="text.secondary" sx={{ color: 'rgba(255, 255, 255, 0.7)' }}>
          Swipe up to unlock
        </Typography>
      </Box>
    </Box>
  );
};

export default Lockscreen; 