import React from 'react';
import {
  Box,
  Typography,
  IconButton,
  Paper,
  Stack,
} from '@mui/material';
import {
  PlayArrow as PlayIcon,
  Pause as PauseIcon,
  SkipNext as NextIcon,
  SkipPrevious as PreviousIcon,
} from '@mui/icons-material';
import { motion } from 'framer-motion';

const Lockscreen = () => {
  return (
    <Box
      sx={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        background: 'linear-gradient(135deg, #1a2332 0%, #0f1419 100%)',
        p: 3,
      }}
    >
      <Box sx={{ textAlign: 'center', mt: 4 }}>
        <Typography variant="h6" color="text.secondary">
          12:34
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Monday, March 18
        </Typography>
      </Box>

      <Box sx={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <Paper
          elevation={3}
          sx={{
            p: 4,
            background: 'rgba(255, 255, 255, 0.08)',
            border: '1.5px solid rgba(255, 255, 255, 0.13)',
            borderRadius: 2,
            width: '100%',
            maxWidth: 400,
          }}
        >
          <Box sx={{ textAlign: 'center', mb: 4 }}>
            <Typography variant="h5" sx={{ mb: 1 }}>
              Cozy Rainy Afternoon
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Generated by Ambiance AI
            </Typography>
          </Box>

          <Stack
            direction="row"
            spacing={3}
            justifyContent="center"
            alignItems="center"
          >
            <IconButton size="large" sx={{ color: 'white' }}>
              <PreviousIcon />
            </IconButton>
            <IconButton
              size="large"
              sx={{
                width: 64,
                height: 64,
                bgcolor: 'primary.main',
                '&:hover': {
                  bgcolor: 'primary.dark',
                },
              }}
            >
              <PlayIcon />
            </IconButton>
            <IconButton size="large" sx={{ color: 'white' }}>
              <NextIcon />
            </IconButton>
          </Stack>
        </Paper>
      </Box>

      <Box sx={{ textAlign: 'center', mb: 4 }}>
        <Typography variant="body2" color="text.secondary">
          Swipe up to unlock
        </Typography>
      </Box>
    </Box>
  );
};

export default Lockscreen; 